### ISSUE TITLE
Comparison of address NSURLIsExcludedFromBackupKey not equal to a pointer is always true

### ISSUE THREAD

**Issue by michaelkamprath** [quantcast/ios-measurement#16]
Line 95 in `QuantcastUtils.m` generates a compile warning for me in Xcode 6.3. The warning is "Comparison of address `NSURLIsExcludedFromBackupKey` not equal to a pointer is always true"

**Comment by SmithKevin** [comment]
Hello @michaelkamprath 
    Thanks for bringing that to our attention.   I will look into it that immediately.

**Comment by SmithKevin** [comment]
Hi Michael,
   So I had some time to look into this further.  In 6.3 Xcode is now doing some extra static analysis based on your projects deployment target.   In this case the constant NSURLIsExcludedFromBackupKey exists in iOS 5.1 and above, so I assume your project has a deployment target greater or equal to 5.1.  Xcode 6.3 now spits out this warning because NSURLIsExcludedFromBackupKey always exists in your project, so that check is technically unnecessary.  The issue is our SDK is compatible with 5.0, so this check is still necessary to support those devices.    I will look into ways to suppress these new type of warnings while still maintaining compatibility.  

In the mean time, if you want to remove the warning, you can delete `&NSURLIsExcludedFromBackupKey != NULL && ` from the if check on line 95 of `QuantcastUtils.m` with no consequences. 

-Kevin

**Comment by michaelkamprath** [comment]
@SmithKevin I am hesitant to modify the SDK code directly. I can wait until an update is released.

**Comment by SmithKevin** [comment]
@michaelkamprath Just wanted to let you know that this issue has been addressed in our newest 1.4.9 release.
